//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDPoverSSH.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDPoverSSH.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete connection{0}?.
        /// </summary>
        public static string ConfirmDeleteConnection {
            get {
                return ResourceManager.GetString("ConfirmDeleteConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter connection name....
        /// </summary>
        public static string ConnectionNameHint {
            get {
                return ResourceManager.GetString("ConnectionNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete connection.
        /// </summary>
        public static string DeleteConnectionCommanDescription {
            get {
                return ResourceManager.GetString("DeleteConnectionCommanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate connection.
        /// </summary>
        public static string DuplicateConnection {
            get {
                return ResourceManager.GetString("DuplicateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export connection (for importing on target machine).
        /// </summary>
        public static string ExportCommandDescription {
            get {
                return ResourceManager.GetString("ExportCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter....
        /// </summary>
        public static string FilterHint {
            get {
                return ResourceManager.GetString("FilterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Connection.
        /// </summary>
        public static string ImportConnection {
            get {
                return ResourceManager.GetString("ImportConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote computer will connect to port {0} on this computer. Click to change direction..
        /// </summary>
        public static string IncomingConnectionDescription {
            get {
                return ResourceManager.GetString("IncomingConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote computer will establish a reverse SSH tunnel to this computer. Click to change direction..
        /// </summary>
        public static string IncomingReverseTunnelDescription {
            get {
                return ResourceManager.GetString("IncomingReverseTunnelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote computer will establish an SSH tunnel to this computer. Click to change direction..
        /// </summary>
        public static string IncomingTunnelDescription {
            get {
                return ResourceManager.GetString("IncomingTunnelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Local Computer).
        /// </summary>
        public static string LocalComputerName {
            get {
                return ResourceManager.GetString("LocalComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Connection.
        /// </summary>
        public static string NewConnection {
            get {
                return ResourceManager.GetString("NewConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer will connect to port {0} on the remote computer. Click to change direction..
        /// </summary>
        public static string OutgoingConnectionDescription {
            get {
                return ResourceManager.GetString("OutgoingConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer will establish a reverse SSH tunnel to the remote computer. Click to change direction..
        /// </summary>
        public static string OutgoingReverseTunnelDescription {
            get {
                return ResourceManager.GetString("OutgoingReverseTunnelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer will establish an SSH tunnel to the remote computer. Click to change direction..
        /// </summary>
        public static string OutgoingTunnelDescription {
            get {
                return ResourceManager.GetString("OutgoingTunnelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RDPoverSSH worker service is not installed. The application may not function as expected..
        /// </summary>
        public static string ServiceNotInstalled {
            get {
                return ResourceManager.GetString("ServiceNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RDPoverSSH worker service is not running. The application may not function as expected..
        /// </summary>
        public static string ServiceNotRunning {
            get {
                return ResourceManager.GetString("ServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show SSH Server Key.
        /// </summary>
        public static string ShowSshServerKey {
            get {
                return ResourceManager.GetString("ShowSshServerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below is the SSH private key for this server. This key allows SSH access to this machine, so share it with care!.
        /// </summary>
        public static string SshPrivateKeyDescription {
            get {
                return ResourceManager.GetString("SshPrivateKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH Server Private Key.
        /// </summary>
        public static string SshServerKeyHeading {
            get {
                return ResourceManager.GetString("SshServerKeyHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
