//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDPoverSSH.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDPoverSSH.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SSH Server Key.
        /// </summary>
        public static string AddSshServerKey {
            get {
                return ResourceManager.GetString("AddSshServerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator privileges are required to view the SSH Server private key..
        /// </summary>
        public static string AdminRequiredForPrivateKey {
            get {
                return ResourceManager.GetString("AdminRequiredForPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator privileges are required to save the SSH Server private key..
        /// </summary>
        public static string AdminRequiredToSavePrivateKey {
            get {
                return ResourceManager.GetString("AdminRequiredToSavePrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change this with care as it has been automatically selected as a currently available port..
        /// </summary>
        public static string ChangeIncomingLocalTunnelPortWarning {
            get {
                return ResourceManager.GetString("ChangeIncomingLocalTunnelPortWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain this value from the remote computer..
        /// </summary>
        public static string ChangeOutgoingLocalTunnelPortWarning {
            get {
                return ResourceManager.GetString("ChangeOutgoingLocalTunnelPortWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete connection{0}?.
        /// </summary>
        public static string ConfirmDeleteConnection {
            get {
                return ResourceManager.GetString("ConfirmDeleteConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tunnel is currently connected..
        /// </summary>
        public static string ConnectedTunnelStatus {
            get {
                return ResourceManager.GetString("ConnectedTunnelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter connection name....
        /// </summary>
        public static string ConnectionNameHint {
            get {
                return ResourceManager.GetString("ConnectionNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete connection.
        /// </summary>
        public static string DeleteConnectionCommanDescription {
            get {
                return ResourceManager.GetString("DeleteConnectionCommanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tunnel has not successfully connected or was connected and became disconnected. Click for more details..
        /// </summary>
        public static string DisconnectedTunnelStatus {
            get {
                return ResourceManager.GetString("DisconnectedTunnelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate connection.
        /// </summary>
        public static string DuplicateConnection {
            get {
                return ResourceManager.GetString("DuplicateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error connecting to {0}:{1}. The details are below..
        /// </summary>
        public static string ErrorConnectingToTunnel {
            get {
                return ResourceManager.GetString("ErrorConnectingToTunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving the SSH Server private key..
        /// </summary>
        public static string ErrorGettingPrivateKey {
            get {
                return ResourceManager.GetString("ErrorGettingPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving the SSH Server private key..
        /// </summary>
        public static string ErrorSavingPrivateKey {
            get {
                return ResourceManager.GetString("ErrorSavingPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export connection (for importing on target machine).
        /// </summary>
        public static string ExportCommandDescription {
            get {
                return ResourceManager.GetString("ExportCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter....
        /// </summary>
        public static string FilterHint {
            get {
                return ResourceManager.GetString("FilterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Connection.
        /// </summary>
        public static string ImportConnection {
            get {
                return ResourceManager.GetString("ImportConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote computer will connect to port {0} on this computer. Click to change direction..
        /// </summary>
        public static string IncomingConnectionDescription {
            get {
                return ResourceManager.GetString("IncomingConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote computer will establish a reverse SSH tunnel to this computer. Click to change direction..
        /// </summary>
        public static string IncomingReverseTunnelDescription {
            get {
                return ResourceManager.GetString("IncomingReverseTunnelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote computer will establish an SSH tunnel to this computer. Click to change direction..
        /// </summary>
        public static string IncomingTunnelDescription {
            get {
                return ResourceManager.GetString("IncomingTunnelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reverse tunnel will route this port on the local machine (localhost:{0}) to the connection port on the remote machine ({1})..
        /// </summary>
        public static string IncomingTunnelLocalTunnelPortDescription {
            get {
                return ResourceManager.GetString("IncomingTunnelLocalTunnelPortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Local Computer).
        /// </summary>
        public static string LocalComputerName {
            get {
                return ResourceManager.GetString("LocalComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Connection.
        /// </summary>
        public static string NewConnection {
            get {
                return ResourceManager.GetString("NewConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer will connect to port {0} on the remote computer. Click to change direction..
        /// </summary>
        public static string OutgoingConnectionDescription {
            get {
                return ResourceManager.GetString("OutgoingConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer will establish a reverse SSH tunnel to the remote computer. Click to change direction..
        /// </summary>
        public static string OutgoingReverseTunnelDescription {
            get {
                return ResourceManager.GetString("OutgoingReverseTunnelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer will establish an SSH tunnel to the remote computer. Click to change direction..
        /// </summary>
        public static string OutgoingTunnelDescription {
            get {
                return ResourceManager.GetString("OutgoingTunnelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reverse tunnel will route this port on the remote machine ({0}) to the connection port on the this machine (localhost:{1})..
        /// </summary>
        public static string OutgoingTunnelLocalTunnelPortDescription {
            get {
                return ResourceManager.GetString("OutgoingTunnelLocalTunnelPortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste the SSH Server&apos;s private key below..
        /// </summary>
        public static string PasteSshServerPrivateKey {
            get {
                return ResourceManager.GetString("PasteSshServerPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Computer.
        /// </summary>
        public static string Remote_Computer {
            get {
                return ResourceManager.GetString("Remote Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RDPoverSSH worker service is not installed. The application may not function as expected..
        /// </summary>
        public static string ServiceNotInstalled {
            get {
                return ResourceManager.GetString("ServiceNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RDPoverSSH worker service is not running. The application may not function as expected..
        /// </summary>
        public static string ServiceNotRunning {
            get {
                return ResourceManager.GetString("ServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show SSH Server Key.
        /// </summary>
        public static string ShowSshServerKey {
            get {
                return ResourceManager.GetString("ShowSshServerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below is the SSH private key for this server. This key allows SSH access to this machine, so share it with care!.
        /// </summary>
        public static string SshPrivateKeyDescription {
            get {
                return ResourceManager.GetString("SshPrivateKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH Server Private Key.
        /// </summary>
        public static string SshServerKeyHeading {
            get {
                return ResourceManager.GetString("SshServerKeyHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH Server private key not found. Please try again.
        ///.
        /// </summary>
        public static string SshServerKeyNotFound {
            get {
                return ResourceManager.GetString("SshServerKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SSH Server private key has not yet been generated. Please try again shortly..
        /// </summary>
        public static string SshServerKeyNotGenerated {
            get {
                return ResourceManager.GetString("SshServerKeyNotGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SSH server is not running. It will be started shortly..
        /// </summary>
        public static string SshServerNotRunning {
            get {
                return ResourceManager.GetString("SshServerNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SSH server is running..
        /// </summary>
        public static string SshServerRunning {
            get {
                return ResourceManager.GetString("SshServerRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state of the SSH server is currently unknown..
        /// </summary>
        public static string SshStateUnknown {
            get {
                return ResourceManager.GetString("SshStateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tunnel status is unknown. If the tunnel configuration was recently changed, a new connection attempt will occur shortly..
        /// </summary>
        public static string UnknownTunnelStatus {
            get {
                return ResourceManager.GetString("UnknownTunnelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
